import assert from "node:assert/strict";
import { appendFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ActionSafety, AmbiguousExternalActionError, OperationJournal, buildOperation } from "../index.mjs";

async function setup() { const root = await mkdtemp(join(tmpdir(), "pi-action-safety-")); return { root, safety: new ActionSafety({ journal: new OperationJournal(root) }) }; }
function spec(key = "send-1", action = "send") { return { sessionId: "session-a", turnRef: "user-entry-a", tool: "telegram_send", action, operationKey: key, args: { peer: "self", text: "test message" } }; }
function fake() { let calls = 0; return { invoke: async operation => ({ status: "sent", message_id: ++calls, operation_id: operation.operation_id }), reconcile: async () => ({ state: "retry" }), get calls() { return calls; } }; }

test("first execution is persisted and repeated logical action is deduplicated", async () => { const x = await setup(); try { const f = fake(); const first = await x.safety.execute(spec(), f); const repeated = await x.safety.execute(spec(), f); assert.equal(f.calls, 1); assert.equal(first.operation.status, "COMPLETED"); assert.equal(repeated.deduplicated, true); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("different logical action has a distinct operation id", async () => { const x = await setup(); try { const f = fake(); await x.safety.execute(spec("send-1"), f); await x.safety.execute(spec("send-2"), f); assert.equal(f.calls, 2); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("stale STARTED reconciles after an external success without a duplicate", async () => { const x = await setup(); try { const f = fake(), op = buildOperation(spec()); await x.safety.journal.save({ ...op, status: "STARTED", created_at: "a", started_at: "a", completed_at: null, result_reference: null, attempt: 1 }); const recovered = await x.safety.execute(spec(), { ...f, reconcile: async operation => ({ state: "completed", result: { status: "sent", message_id: 7, operation_id: operation.operation_id } }) }); assert.equal(f.calls, 0); assert.equal(recovered.reconciled, true); assert.equal((await x.safety.journal.get(op.operation_id)).status, "COMPLETED"); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("stale STARTED only retries after reconciliation proves it safe", async () => { const x = await setup(); try { const f = fake(), op = buildOperation(spec()); await x.safety.journal.save({ ...op, status: "STARTED", created_at: "a", started_at: "a", completed_at: null, result_reference: null, attempt: 1 }); await x.safety.execute(spec(), f); assert.equal(f.calls, 1); assert.equal((await x.safety.journal.get(op.operation_id)).attempt, 2); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("ambiguous stale action becomes UNKNOWN and is never blindly retried", async () => { const x = await setup(); try { const f = fake(), op = buildOperation(spec()); await x.safety.journal.save({ ...op, status: "STARTED", created_at: "a", started_at: "a", completed_at: null, result_reference: null, attempt: 1 }); await assert.rejects(() => x.safety.execute(spec(), { ...f, reconcile: async () => ({ state: "unknown", reason: "no state evidence" }) }), AmbiguousExternalActionError); assert.equal(f.calls, 0); assert.equal((await x.safety.journal.get(op.operation_id)).status, "UNKNOWN"); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("journal records are private, atomic, and ignore an incomplete temporary tail", async () => { const x = await setup(); try { const f = fake(); const result = await x.safety.execute(spec(), f); const file = x.safety.journal.path(result.operation.operation_id); assert.equal((await (await import("node:fs/promises")).stat(file)).mode & 0o777, 0o600); await writeFile(`${file}.partial.tmp`, "{broken", { mode: 0o600 }); assert.equal((await x.safety.journal.get(result.operation.operation_id)).status, "COMPLETED"); const raw = await readFile(file, "utf8"); assert.doesNotMatch(raw, /test message|authorization|bearer|api_key|password|self/i); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("journal stores no target, invite, bearer, password, or message content", async () => { const x = await setup(); try { const safety = new ActionSafety({ journal: new OperationJournal(x.root) }); const input = { ...spec("secret-safe"), args: { peer: "https://t.me/+private-invite", text: "Bearer top-secret password=hunter2" } }; await safety.execute(input, fake()); const raw = await readFile((await safety.journal.list())[0] && safety.journal.path((await safety.journal.list())[0].operation_id), "utf8"); assert.doesNotMatch(raw, /private-invite|top-secret|hunter2|Bearer/i); assert.match(raw, /normalized_arguments_hash/); } finally { await rm(x.root, { recursive: true, force: true }); } });
test("concurrent lookup and update executes one external action", async () => { const x = await setup(); try { const f = fake(); await Promise.all(Array.from({ length: 8 }, () => x.safety.execute(spec(), f))); assert.equal(f.calls, 1); } finally { await rm(x.root, { recursive: true, force: true }); } });
for (const action of ["send", "reply", "forward", "edit", "delete", "react", "join", "leave"]) test(`mock Telegram ${action} uses completed reconciliation`, async () => { const x = await setup(); try { const f = fake(), s = spec(`${action}-1`, action), op = buildOperation(s); await x.safety.journal.save({ ...op, status: "STARTED", created_at: "a", started_at: "a", completed_at: null, result_reference: null, attempt: 1 }); const result = await x.safety.execute(s, { ...f, reconcile: async () => ({ state: "completed", result: { status: action === "leave" ? "left" : "done" } }) }); assert.equal(result.reconciled, true); assert.equal(f.calls, 0); } finally { await rm(x.root, { recursive: true, force: true }); } });
for (const point of ["before_planned", "after_planned", "after_started", "after_completed"]) test(`fault point ${point} is deterministic`, async () => { const x = await setup(); try { const f = fake(); const old = process.env.PI_ACTION_SAFETY_FAULT; const oldMode = process.env.PI_ACTION_SAFETY_FAULT_MODE; process.env.PI_ACTION_SAFETY_FAULT = point; process.env.PI_ACTION_SAFETY_FAULT_MODE = "throw"; await assert.rejects(() => x.safety.execute(spec(), f), new RegExp(point)); old === undefined ? delete process.env.PI_ACTION_SAFETY_FAULT : process.env.PI_ACTION_SAFETY_FAULT = old; oldMode === undefined ? delete process.env.PI_ACTION_SAFETY_FAULT_MODE : process.env.PI_ACTION_SAFETY_FAULT_MODE = oldMode; } finally { delete process.env.PI_ACTION_SAFETY_FAULT; delete process.env.PI_ACTION_SAFETY_FAULT_MODE; await rm(x.root, { recursive: true, force: true }); } });
test("after-external SIGKILL leaves STARTED for a new process to reconcile", async () => { const root = await mkdtemp(join(tmpdir(), "pi-action-safety-kill-")); const fixture = join(root, "child.mjs"); try { await writeFile(fixture, `import { ActionSafety, OperationJournal } from ${JSON.stringify(new URL("../index.mjs", import.meta.url).href)}; const s=new ActionSafety({journal:new OperationJournal(process.env.ROOT)}); await s.execute(${JSON.stringify(spec())},{invoke:async()=>({status:'sent'}),reconcile:async()=>({state:'retry'})});`); const child = await new Promise(resolve => { const p = spawn(process.execPath, [fixture], { env: { ...process.env, ROOT: root, PI_ACTION_SAFETY_FAULT: "after_external" } }); p.on("close", (code, signal) => resolve({ code, signal })); }); assert.equal(child.signal, "SIGKILL"); const safety = new ActionSafety({ journal: new OperationJournal(root) }); const f = fake(); const recovered = await safety.execute(spec(), { ...f, reconcile: async () => ({ state: "completed", result: { status: "sent", message_id: 1 } }) }); assert.equal(recovered.reconciled, true); assert.equal(f.calls, 0); } finally { await rm(root, { recursive: true, force: true }); } });
test("E2E JSONL session resume reconciles successful write and continues next step", async () => {
  const root = await mkdtemp(join(tmpdir(), "pi-action-safety-e2e-"));
  const fixture = join(root, "worker.mjs");
  const sessionFile = join(root, "session.jsonl");
  const s = spec("e2e-send", "send");
  try {
    await writeFile(sessionFile, `${JSON.stringify({ type: "session", version: 3, id: "session-a" })}\n${JSON.stringify({ type: "message", id: "call-1", parentId: null, message: { role: "assistant", content: [{ type: "toolCall", id: "call-1", name: "telegram_send", arguments: { peer: "self", text: "test message" } }] } })}\n`);
    await writeFile(fixture, `import { appendFile, readFile } from "node:fs/promises"; import { ActionSafety, OperationJournal } from ${JSON.stringify(new URL("../index.mjs", import.meta.url).href)}; const root=process.env.ROOT; const s=new ActionSafety({journal:new OperationJournal(root)}); await s.execute(${JSON.stringify(s)},{invoke:async operation=>{const file=root+'/external-count'; const n=Number((await readFile(file,'utf8').catch(()=> '0'))||0)+1; await appendFile(file,String(n)); return {status:'sent',message_id:9,operation_id:operation.operation_id};},reconcile:async()=>({state:'retry'})});`);
    const child = await new Promise(resolve => { const p = spawn(process.execPath, [fixture], { env: { ...process.env, ROOT: root, PI_ACTION_SAFETY_FAULT: "after_external" } }); p.on("close", (code, signal) => resolve({ code, signal })); });
    assert.equal(child.signal, "SIGKILL");
    const resumed = new ActionSafety({ journal: new OperationJournal(root) });
    const reconciled = await resumed.execute(s, { invoke: async () => { throw new Error("duplicate write"); }, reconcile: async () => Number(await readFile(join(root, "external-count"), "utf8")) === 1 ? { state: "completed", result: { status: "sent", message_id: 9 } } : { state: "unknown" } });
    assert.equal(reconciled.reconciled, true);
    await appendFile(sessionFile, `${JSON.stringify({ type: "message", id: "next-step", parentId: "call-1", message: { role: "toolResult", toolName: "task", content: [{ type: "text", text: "NEXT_STEP_CONTINUED" }], isError: false } })}\n`);
    assert.equal(await readFile(join(root, "external-count"), "utf8"), "1");
    assert.match(await readFile(sessionFile, "utf8"), /NEXT_STEP_CONTINUED/);
  } finally { await rm(root, { recursive: true, force: true }); }
});

test("invoke failure after a landed write is closed by reconciliation evidence", async () => { const x = await setup(); try { let calls = 0; const result = await x.safety.execute(spec("parse-fail"), { invoke: async () => { calls += 1; throw new Error("bad updates result"); }, reconcile: async () => ({ state: "completed", result: { status: "already_edited", message_id: 42 } }) }); assert.equal(calls, 1); assert.equal(result.reconciled, true); assert.equal(result.operation.status, "COMPLETED"); assert.equal(result.operation.result_reference.message_id, 42); } finally { await rm(x.root, { recursive: true, force: true }); } });

test("invoke failure proven not to have landed becomes FAILED and surfaces the error", async () => { const x = await setup(); try { await assert.rejects(() => x.safety.execute(spec("real-fail"), { invoke: async () => { throw new Error("PREMIUM_ACCOUNT_REQUIRED"); }, reconcile: async () => ({ state: "retry", reason: "not present" }) }), /PREMIUM_ACCOUNT_REQUIRED/); const [record] = await x.safety.journal.list(); assert.equal(record.status, "FAILED"); } finally { await rm(x.root, { recursive: true, force: true }); } });

test("invoke failure with no evidence stays UNKNOWN and blocks a blind retry", async () => { const x = await setup(); try { await assert.rejects(() => x.safety.execute(spec("no-evidence"), { invoke: async () => { throw new Error("timeout"); }, reconcile: async () => ({ state: "unknown", reason: "cannot verify" }) }), AmbiguousExternalActionError); const [record] = await x.safety.journal.list(); assert.equal(record.status, "UNKNOWN"); } finally { await rm(x.root, { recursive: true, force: true }); } });

test("journal errors never retain account identifiers or protocol dumps", async () => { const x = await setup(); try { const dump = "tg: callback: edit: bad updates result [UpdateEditMessage{PeerID:PeerUser{UserID:1234567890}\nSavedPeerID:PeerUser{UserID:1234567890}}] phone=70000000000"; await assert.rejects(() => x.safety.execute(spec("dump-error"), { invoke: async () => { throw new Error(dump); }, reconcile: async () => ({ state: "unknown" }) }), AmbiguousExternalActionError); const [record] = await x.safety.journal.list(); const raw = JSON.stringify(record); assert.doesNotMatch(raw, /1234567890|70000000000/); assert.ok(record.last_error.length <= 200); } finally { await rm(x.root, { recursive: true, force: true }); } });
